### PR TITLE
Structured logging RFC

### PR DESCRIPTION
**Pull request by m-allanson**
[View formatted](https://github.com/gatsbyjs/rfcs/blob/7d87e12dbb34ed437aa12729c482ba9419cd13db/text/000-structured-logging.md)

### CODE REVIEW

**Comment by stefanprobst** [comment]
* I like that logging is handled by a redux action. This would also make it easier to find a uniform approach to how we log (validation) errors in action creators.
* I don't think it's necessary to run the actions through the redux store. We could just catch log actions in a middleware and call the logger instance with the message there. So we'd have (i) a `SET_LOGGER` action that stores the logger instance in app state, and a `LOG_MESSAGE` action; (ii) a redux middleware that does something like `store.getState().logger(action.payload)` and does not call next().
* Logging before the store is available (during early bootstrap?): would just use the logger instance directly.

**Comment by stefanprobst** [comment]
This is what it could look like with a middleware, and dispatching log actions. The only place where the old reporter is still directly imported is in `bootstrap/index` (and in the `commands` which haven't been touched).

https://github.com/gatsbyjs/gatsby/compare/master...stefanprobst:redux-logger-middleware

Note: Not sure what the scope of the RFC actually is -- the above is not about displaying/formatting/persisting logs, but about forwarding log messages (and potentially every dispatched action) to a logger instance.

**Comment by stefanprobst** [comment]
This RFC has entered the final comment period.

**Comment by stefanprobst** [comment]
Some discussion on this in https://github.com/gatsbyjs/gatsby/pull/13269

**Comment by agentofuser** [comment]
Regarding indexed error messages, I think TypeScript is a great example: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json

Having unique error codes greatly helps searching the web for help. It also enables localization of error messages down the line.

**Pull request merged**
