### PR TITLE
RFC: Automate Contributor Onboarding RFC

### PR DESCRIPTION
**Pull request by m-allanson**
[View text](https://github.com/gatsbyjs/rfcs/blob/automate-contributor-onboarding/text/0000-automate-contributor-onboarding.md)

### CODE REVIEW

**Comment by SD10** [comment]
Hey everyone,
I'm a member of the [danger](https://github.com/danger) team and I'm super excited to see this discussion. 

You mentioned the Styled Components CONTRIBUTING document. I believe they adopted and extended this document from the Moya organization. 

You can find more information about how we run the Moya organization in our [contributors repo](https://github.com/Moya/contributors). IMO, these guidelines are the reason why Moya has achieved such an amazing community.

Originally, the Moya organization developed a tool called [Aeryn](https://github.com/Moya/Aeryn) to automatically invite contributors to the organization after their first merged PR. 

However, we have since migrated to using an [aeryn.ts file](https://github.com/Moya/moya-peril/blob/master/org/aeryn.ts) with [Peril](https://github.com/danger/peril) because it scales better across all repos in the organization. Peril also has the added benefit of allowing you to write scripts to automate other things around the org.

If you need any help setting up and maintaining this tooling just give me a ping 😃

**Comment by m-allanson** [comment]
Hey @SD10 that's really useful, thanks! I haven't had a chance to get back to this yet, but will keep you in mind when I do :)

**Comment by m-allanson** [comment]
This has been implemented by @jlengstorf 🎉, however the implementation details are slightly different than how this RFC was written up. 

What's the correct thing to do - link to the live implementation and then merge this as-is? Or fully update this to match how it was implemented?

**Comment by jlengstorf** [comment]
Maybe we merge this and I open a PR to modify it? @KyleAMathews what's protocol here?

**Comment by KyleAMathews** [comment]
Hmmm we did do this — but since we didn't merge this at the time, closing it for now — the PR will still be around for historical interest.

**Pull request closed without merging**
