### PR TITLE
[rfc]: start collecting telemetry data

### PR DESCRIPTION
**Pull request by KyleAMathews**
[rendered view](https://github.com/gatsbyjs/rfcs/blob/analytics/text/0000-telemetry.md)

### CODE REVIEW

**Comment by mikl** [comment]
> We could do opt-in instead of opt-out but that would mean most people wouldn't ever know to opt-in and our data collection would be probably useless as we'd only see a small % of user activity and never be sure what % it is of the real total.

Opt-in is certainly less convenient for Gatsby, Inc., but having Gatsby start to “phone home” without consent is seriously creepy, and might even be illegal in some jurisdictions.

You could probably attain reasonable rates of opt-in if you had gatsby-cli ask the user to opt in, on first run and/or while setting up a new project. That’s how ember-cli does it, if memory serves.

**Comment by wincent** [comment]
> A Gatsby machine ID, a randomly generated UUID and stored at ~/.config/gatsby. This does not allow us to track individual users but does enable us to accurately measure user counts vs. event counts.

May not be as accurate as you think, given that many operations may run in temporary "throwaway" environments (eg. CI VMs).

**Comment by KyleAMathews** [comment]
@mikl hey, definitely appreciate your concerns. Curious how you'd compare our approach to what VS Code does? https://code.visualstudio.com/docs/supporting/FAQ#_gdpr-and-vs-code

**Comment by KyleAMathews** [comment]
@wincent it's fairly straightforward to detect when you're in a CI or not https://www.npmjs.com/package/is-ci

So we should be able to generally distinguish between CI builds and normal usage.

**Comment by shrop** [comment]
I am one of those who opts-out of every tracking I possibly can. :) I prefer opt-in, but definitely see the issues there. Related to @mikl's comment, I wonder how this complies with GDPR. I imagine having purely anonymized data goes a long way towards that.

As someone who works at an agency using Gatsby, I have real interest in this kind of work to make sure we don't have larger enterprises block usage of Gatsby. I think just having this conversation in the community goes a long way to deal with those concerns. Thank you!

Suggestions:

* If opt-out is the way to have better tracking, then opt-ing out methods should be discussed here so it is really obvious how to do it for the Gatsby user, with possible reminders. That can be planned as part of the system. UI for opt-out should be clear and understandable too. All of that is just talking through the process.
* Will the analytics code be open source 100%? I think there is value with that from a level of transparency. I am talking more on the side of what is sent and how it is gathered. I am sure Gatsby, Inc. will have closed source analytics on their side and that is understandable. Same as any Gatsby paid services they may/may not have in the future.
> In the future, we’ll create public dashboards with aggregated data from Gatsby usage so the entire community can view the health of various Gatsby ecosystem properties and pitch in to help improve them. A future RFC will cover this work.

I really like this as it goes a long way to transparency of the process and could provide valuable data back to the developer community. Lots of potential there.

**Comment by KyleAMathews** [comment]
>Will the analytics code be open source 100%? I think there is value with that from a level of transparency. I am talking more on the side of what is sent and how it is gathered. I am sure Gatsby, Inc. will have closed source analytics on their side and that is understandable. Same as any Gatsby paid services they may/may not have in the future.

Yes! Forgot to put that in the RFC. We'll also add a test suite to ensure different ways that private information can leak (e.g. path names in error traces) are correctly removed.

https://github.com/gatsbyjs/rfcs/pull/33/commits/92d354232bf48012d2d47cd28c001d21db517147

**Comment by KyleAMathews** [comment]
> I wonder how this complies with GDPR. I imagine having purely anonymized data goes a long way towards that.

Yeah, that's our understanding. VS Code has a similar understanding https://code.visualstudio.com/docs/supporting/FAQ#_gdpr-and-vs-code

**Comment by mikl** [comment]
@KyleAMathews I'm not fond of VSC's phoning home either, if that's what you're asking. As for the legal dimension, you'd probably need some very expensive lawyers to gauge that, and be very very sure you're not logging IP-addresses anywhere, even by accident in some standard nginx request log.

**Comment by KyleAMathews** [comment]
> be very very sure you're not logging IP-addresses anywhere, even by accident in some standard nginx request log.

Indeed!

**Comment by mathieudutour** [comment]
In addition to hiding opting-in/out behind a specific command (which leads to either tracking people behind their back or not having anyone helping to make decisions), it could be a prompt on the post-install script with an explicit question and a link to relevant information

**Comment by jlengstorf** [comment]
> prompt on the post-install script

The balance we want to strike is making sure we're not annoying (see also: GDPR cookie banners) while also letting everyone know what's happening.

One potential solution could be to use something like [configstore](https://www.npmjs.com/package/configstore) and prompt if no choice has been made, then respect that setting globally.

This brings up a question, though: should we allow per-site opt-outs?

**Comment by DSchau** [comment]
This RFC has entered the final comment period. We've heard each of you loud and clear, and we intend to roll this feature out transparently and in the open (it's even one of our [core values](https://www.gatsbyjs.org/blog/2018-09-07-gatsby-values/#work-in-the-open)).

Over the next few days, if there are any other concerns or feedback that we haven't addressed, please let that feedback be known.

We appreciate it more than you know.

Thank you! 💜

**Comment by DSchau** [comment]
Merging this--will implement soon.

One important note is that the pull request implementing the tooling powering this telemetry data will be _in the open_ e.g. a PR to gatsbyjs/gatsby.

Thanks to everyone thus far for all your questions, comments, and concerns. Can't emphasize enough how much we appreciate it!

Thank you!

**Pull request merged**
